export interface Project {
  id: string;
  name: string;
  description: string;
  category: string;
  founder: string;
  founderTwitter: string;
  url: string;
  batch: string;
  tags: string[];
  logo: string;
  source?: string;
}

export interface Founder {
  id: string;
  name: string;
  twitter: string;
  avatar: string;
  role: string;
  project: string;
}

export const DEVFOLIO_LINKS = {
  baseBatchIndia: "https://base-batch-india.devfolio.co/projects",
  builderTrack002: "https://base-batches-builder-track.devfolio.co/projects",
  basedIndia: "https://based-india.devfolio.co/projects",
  buildOnchainFBI: "https://build-onchain-fbi.devfolio.co/projects",
} as const;

export const TG_BOT_LINK = "https://t.me/awesome_base_India_bot";

export const categories = [
  "All",
  "AI",
  "Consumer",
  "DeFi",
  "Gaming",
  "Infra",
  "Mini-apps",
  "NFT",
  "DAO",
  "Identity",
  "Social",
  "Payments",
] as const;

export const batches = [
  "All Batches",
  "Base Batch India",
  "Based India",
  "Builder Track 002",
  "Build Onchain FBI",
  "Independent",
] as const;

export const projects: Project[] = [
  {
    id: "1",
    name: "NOICE",
    description:
      "Turns every social interaction into income. Set-and-forget micropayment tipping on Farcaster and Coinbase Wallet. 5,000 users have tipped 1.4 million times in 30 days.",
    category: "Consumer",
    founder: "Srijan A",
    founderTwitter: "srijancse",
    url: "https://devfolio.co/projects/noice-fd34",
    batch: "Base Batch India",
    tags: ["micropayments", "farcaster", "tipping", "social"],
    logo: "N",
    source: "https://devfolio.co/projects/noice-fd34",
  },
  {
    id: "2",
    name: "JesseGPT",
    description:
      "AI chatbot fine-tuned on Jesse Pollak. Pitch your project idea, get a rating or a roast, and mint your pitch as an ideacoin on Zora. Used as an official judge during Base Batches.",
    category: "AI",
    founder: "Devfolio Team",
    founderTwitter: "devaborin",
    url: "https://jessegpt.xyz",
    batch: "Base Batch India",
    tags: ["AI", "chatbot", "jesse-pollak", "zora"],
    logo: "J",
    source: "https://devfolio.co/projects/jessegpt-2acd",
  },
  {
    id: "3",
    name: "Creatorbase",
    description:
      "Connects brands with creators on the blockchain. Revolutionizes UGC campaigns across TikTok, X, and Facebook with AI automation, onchain verification, and instant payments.",
    category: "Consumer",
    founder: "Creatorbase Team",
    founderTwitter: "creatorbasepro",
    url: "https://creatorbase.pro",
    batch: "Base Batch India",
    tags: ["creator-economy", "UGC", "brands", "payments"],
    logo: "C",
    source: "https://base-batch-india.devfolio.co/projects",
  },
  {
    id: "4",
    name: "Hook-Tuah",
    description:
      "DeFi tooling built around Uniswap v4 hooks on Base. Simplifies custom hook deployment and testing for developers building advanced AMM strategies onchain.",
    category: "DeFi",
    founder: "Hook-Tuah Team",
    founderTwitter: "hooktuah_base",
    url: "https://base-batch-india.devfolio.co/projects",
    batch: "Base Batch India",
    tags: ["uniswap-v4", "hooks", "DeFi", "dev-tools"],
    logo: "H",
    source: "https://base-batch-india.devfolio.co/projects",
  },
  {
    id: "5",
    name: "Clip",
    description:
      "Short-form video platform with onchain engagement rewards. Creators earn directly from views and interactions, with transparent revenue sharing settled on Base.",
    category: "Consumer",
    founder: "Clip Team",
    founderTwitter: "cliponbase",
    url: "https://base-batch-india.devfolio.co/projects",
    batch: "Base Batch India",
    tags: ["video", "content", "creator", "rewards"],
    logo: "Cl",
    source: "https://base-batch-india.devfolio.co/projects",
  },
  {
    id: "6",
    name: "Not Your Type",
    description:
      "AI-powered consumer app that reimagines how users interact with onchain content. Personalized discovery and recommendation engine built natively on Base.",
    category: "AI",
    founder: "NYT Team",
    founderTwitter: "notyourtype_",
    url: "https://base-batch-india.devfolio.co/projects",
    batch: "Base Batch India",
    tags: ["AI", "discovery", "consumer", "personalization"],
    logo: "NY",
    source: "https://base-batch-india.devfolio.co/projects",
  },
  {
    id: "7",
    name: "replyguy",
    description:
      "AI agent that monitors social media conversations and generates context-aware replies to promote onchain projects. Automates community engagement across X and Farcaster.",
    category: "AI",
    founder: "replyguy Team",
    founderTwitter: "replyguyai",
    url: "https://base-batch-india.devfolio.co/projects",
    batch: "Base Batch India",
    tags: ["AI-agent", "social-media", "marketing", "automation"],
    logo: "R",
    source: "https://base-batch-india.devfolio.co/projects",
  },
  {
    id: "8",
    name: "AuditHook",
    description:
      "AI agent that audits Base smart contracts with deep expertise in Uniswap v4 hooks. Provides security analysis, gas optimization, and educational resources for developers.",
    category: "DeFi",
    founder: "AuditHook Team",
    founderTwitter: "audithook_",
    url: "https://devfolio.co/projects/audithook-4602",
    batch: "Base Batch India",
    tags: ["security", "audit", "AI", "uniswap-v4"],
    logo: "A",
    source: "https://devfolio.co/projects/audithook-4602",
  },
  {
    id: "9",
    name: "Kuri",
    description:
      "Onchain savings and chit-fund protocol inspired by traditional Indian community savings circles. Trustless group savings with automated payouts on Base.",
    category: "DeFi",
    founder: "Kuri Team",
    founderTwitter: "kuri_onchain",
    url: "https://base-batch-india.devfolio.co/projects",
    batch: "Base Batch India",
    tags: ["savings", "chit-fund", "community", "DeFi"],
    logo: "K",
    source: "https://base-batch-india.devfolio.co/projects",
  },
  {
    id: "10",
    name: "BitMore",
    description:
      "DeFi investment platform that helps users earn more from their crypto holdings on Base through automated yield strategies and smart portfolio management.",
    category: "DeFi",
    founder: "BitMore Team",
    founderTwitter: "bitmore_fi",
    url: "https://base-batch-india.devfolio.co/projects",
    batch: "Base Batch India",
    tags: ["yield", "investment", "portfolio", "DeFi"],
    logo: "B",
    source: "https://base-batch-india.devfolio.co/projects",
  },
  {
    id: "11",
    name: "A$CE",
    description:
      "Crypto payments and trading tool with a focus on stablecoin transfers. Fast onramp/offramp solution for Indian users on Base with low fees.",
    category: "Payments",
    founder: "A$CE Team",
    founderTwitter: "ace_onbase",
    url: "https://base-batch-india.devfolio.co/projects",
    batch: "Base Batch India",
    tags: ["payments", "stablecoin", "onramp", "trading"],
    logo: "A$",
    source: "https://base-batch-india.devfolio.co/projects",
  },
  {
    id: "12",
    name: "Lotry",
    description:
      "Provably fair onchain lottery and raffle system on Base. Transparent draws with verifiable randomness and instant prize distribution via smart contracts.",
    category: "Gaming",
    founder: "Lotry Team",
    founderTwitter: "lotry_xyz",
    url: "https://base-batch-india.devfolio.co/projects",
    batch: "Base Batch India",
    tags: ["lottery", "raffle", "randomness", "gaming"],
    logo: "L",
    source: "https://base-batch-india.devfolio.co/projects",
  },
  {
    id: "13",
    name: "Darkest Dungeon",
    description:
      "Onchain dungeon crawler game built on Base. Explore procedurally generated dungeons, collect NFT loot, and compete in leaderboard challenges with real stakes.",
    category: "Gaming",
    founder: "Darkest Dungeon Team",
    founderTwitter: "darkestdungeon_",
    url: "https://base-batch-india.devfolio.co/projects",
    batch: "Base Batch India",
    tags: ["gaming", "dungeon-crawler", "NFT", "play-to-earn"],
    logo: "DD",
    source: "https://base-batch-india.devfolio.co/projects",
  },
  {
    id: "14",
    name: "LiquidStake",
    description: "Liquid staking derivatives on Base. Stake ETH, get lsETH, earn yield while staying liquid.",
    category: "DeFi",
    founder: "Manish Rao",
    founderTwitter: "manishdefi",
    url: "https://liquidstake.fi",
    batch: "Builder Track 002",
    tags: ["staking", "yield"],
    logo: "LS",
    source: DEVFOLIO_LINKS.builderTrack002,
  },
  {
    id: "15",
    name: "PixelCraft",
    description: "Collaborative onchain pixel art canvas. Create, own, and trade pixel art NFTs on Base.",
    category: "NFT",
    founder: "Tanya Bhatt",
    founderTwitter: "tanyapixels",
    url: "https://pixelcraft.art",
    batch: "Base Batch India",
    tags: ["NFT", "art", "collab"],
    logo: "PC",
    source: DEVFOLIO_LINKS.baseBatchIndia,
  },
  {
    id: "16",
    name: "BaseVault",
    description: "Multi-sig treasury management for DAOs on Base. Gasless approvals with social recovery.",
    category: "DAO",
    founder: "Siddharth Menon",
    founderTwitter: "sidmenon",
    url: "https://basevault.xyz",
    batch: "Builder Track 002",
    tags: ["treasury", "multisig"],
    logo: "BV",
    source: DEVFOLIO_LINKS.builderTrack002,
  },
  {
    id: "17",
    name: "QuickPay",
    description: "Cross-border payment rails for freelancers. Get paid globally, settle on Base instantly.",
    category: "Payments",
    founder: "Rashmi Iyer",
    founderTwitter: "rashmipays",
    url: "https://quickpay.base",
    batch: "Base Batch India",
    tags: ["payments", "freelance"],
    logo: "QP",
    source: DEVFOLIO_LINKS.baseBatchIndia,
  },
  {
    id: "18",
    name: "DeSci India",
    description: "Decentralized science funding platform. Indian researchers publish and get funded on Base.",
    category: "Social",
    founder: "Arun Krishnan",
    founderTwitter: "arunkris",
    url: "https://desci.in",
    batch: "Builder Track 002",
    tags: ["DeSci", "research"],
    logo: "DS",
    source: DEVFOLIO_LINKS.builderTrack002,
  },
  {
    id: "19",
    name: "BaseOracle",
    description: "Decentralized oracle network optimized for Base. Low-latency price feeds for DeFi.",
    category: "Infra",
    founder: "Nikhil Gupta",
    founderTwitter: "nikhiloracle",
    url: "https://baseoracle.xyz",
    batch: "Builder Track 002",
    tags: ["oracle", "infra"],
    logo: "BO",
    source: DEVFOLIO_LINKS.builderTrack002,
  },
  {
    id: "20",
    name: "GigBase",
    description: "Decentralized gig marketplace. Post jobs, complete tasks, get paid in crypto on Base.",
    category: "Social",
    founder: "Meera Shah",
    founderTwitter: "meeragigs",
    url: "https://gigbase.work",
    batch: "Base Batch India",
    tags: ["gig", "marketplace"],
    logo: "GB",
    source: DEVFOLIO_LINKS.baseBatchIndia,
  },
  {
    id: "21",
    name: "BaseAI",
    description: "AI model marketplace on Base. Buy, sell, and rent AI compute using onchain credits.",
    category: "AI",
    founder: "Varun Taneja",
    founderTwitter: "varunai",
    url: "https://baseai.dev",
    batch: "Builder Track 002",
    tags: ["AI", "compute"],
    logo: "BA",
    source: DEVFOLIO_LINKS.builderTrack002,
  },
  {
    id: "22",
    name: "Fundbase",
    description: "Onchain crowdfunding for Indian startups. Raise from global investors, tracked on Base.",
    category: "DeFi",
    founder: "Pooja Rajan",
    founderTwitter: "poojafund",
    url: "https://fundbase.xyz",
    batch: "Base Batch India",
    tags: ["crowdfunding", "invest"],
    logo: "FB",
    source: DEVFOLIO_LINKS.baseBatchIndia,
  },
  {
    id: "23",
    name: "NFTix",
    description: "Event ticketing on Base. Verifiable tickets as NFTs with built-in resale royalties.",
    category: "NFT",
    founder: "Sahil Mehta",
    founderTwitter: "sahiltix",
    url: "https://nftix.events",
    batch: "Builder Track 002",
    tags: ["tickets", "events"],
    logo: "NT",
    source: DEVFOLIO_LINKS.builderTrack002,
  },
  {
    id: "24",
    name: "BaseRent",
    description: "Tokenized real estate rentals. Security deposits and rent payments as smart contracts on Base.",
    category: "DeFi",
    founder: "Lakshmi Subramanian",
    founderTwitter: "lakshmirent",
    url: "https://baserent.in",
    batch: "Base Batch India",
    tags: ["real-estate", "rental"],
    logo: "BR",
    source: DEVFOLIO_LINKS.baseBatchIndia,
  },
  {
    id: "25",
    name: "LearnBase",
    description: "Learn-to-earn education platform. Complete Web3 courses, earn credentials as NFTs on Base.",
    category: "Social",
    founder: "Ankita Das",
    founderTwitter: "ankitalearns",
    url: "https://learnbase.xyz",
    batch: "Builder Track 002",
    tags: ["education", "learn-to-earn"],
    logo: "LB",
    source: DEVFOLIO_LINKS.builderTrack002,
  },
  {
    id: "26",
    name: "BaseBridge",
    description: "One-click bridge between Ethereum L1 and Base. Optimized for speed and low fees.",
    category: "Infra",
    founder: "Gaurav Thakur",
    founderTwitter: "gauravbridge",
    url: "https://basebridge.xyz",
    batch: "Base Batch India",
    tags: ["bridge", "L2"],
    logo: "BB",
    source: DEVFOLIO_LINKS.baseBatchIndia,
  },
  {
    id: "27",
    name: "DexTracker",
    description: "Real-time DEX analytics for Base. Track volume, TVL, and whale movements.",
    category: "Infra",
    founder: "Ravi Shankar",
    founderTwitter: "ravianalytics",
    url: "https://dextracker.base",
    batch: "Builder Track 002",
    tags: ["analytics", "DEX"],
    logo: "DT",
    source: DEVFOLIO_LINKS.builderTrack002,
  },
  {
    id: "28",
    name: "SocialFi",
    description: "Creator monetization protocol. Fans buy social tokens of their favorite creators on Base.",
    category: "Social",
    founder: "Simran Kaur",
    founderTwitter: "simransocial",
    url: "https://socialfi.base",
    batch: "Base Batch India",
    tags: ["creator", "social-tokens"],
    logo: "SF",
    source: DEVFOLIO_LINKS.baseBatchIndia,
  },
  {
    id: "29",
    name: "YieldFarm",
    description: "Auto-compounding yield aggregator for Base DeFi protocols. Set-and-forget farming.",
    category: "DeFi",
    founder: "Harsh Vardhan",
    founderTwitter: "harshyield",
    url: "https://yieldfarm.fi",
    batch: "Builder Track 002",
    tags: ["yield", "farming"],
    logo: "YF",
    source: DEVFOLIO_LINKS.builderTrack002,
  },
  {
    id: "30",
    name: "BaseQuiz",
    description: "Trivia-to-earn gaming on Base. Daily quizzes with real crypto prizes.",
    category: "Gaming",
    founder: "Deepak Jain",
    founderTwitter: "deepakquiz",
    url: "https://basequiz.fun",
    batch: "Base Batch India",
    tags: ["quiz", "gaming"],
    logo: "BQ",
    source: DEVFOLIO_LINKS.baseBatchIndia,
  },
  {
    id: "31",
    name: "WalletGuard",
    description: "Smart contract wallet with built-in phishing detection and transaction simulation on Base.",
    category: "Infra",
    founder: "Ananya Mishra",
    founderTwitter: "ananyasec",
    url: "https://walletguard.base",
    batch: "Builder Track 002",
    tags: ["wallet", "security"],
    logo: "WG",
    source: DEVFOLIO_LINKS.builderTrack002,
  },
  {
    id: "32",
    name: "TokenVote",
    description: "Governance-as-a-service for Base projects. Snapshot-style voting with onchain execution.",
    category: "DAO",
    founder: "Kunal Verma",
    founderTwitter: "kunalvotes",
    url: "https://tokenvote.xyz",
    batch: "Base Batch India",
    tags: ["governance", "voting"],
    logo: "TV",
    source: DEVFOLIO_LINKS.baseBatchIndia,
  },
  {
    id: "33",
    name: "StreamPay",
    description: "Real-time salary streaming on Base. Get paid every second instead of every month.",
    category: "Payments",
    founder: "Nandini Roy",
    founderTwitter: "nandinistream",
    url: "https://streampay.fi",
    batch: "Builder Track 002",
    tags: ["streaming", "payroll"],
    logo: "SP",
    source: DEVFOLIO_LINKS.builderTrack002,
  },
  {
    id: "34",
    name: "AIAgent",
    description: "Autonomous AI agents that trade, stake, and manage DeFi portfolios on Base for you.",
    category: "AI",
    founder: "Akash Reddy",
    founderTwitter: "akashagent",
    url: "https://aiagent.base",
    batch: "Builder Track 002",
    tags: ["AI", "agents", "DeFi"],
    logo: "AA",
    source: DEVFOLIO_LINKS.builderTrack002,
  },
  {
    id: "35",
    name: "BaseENS",
    description: "Affordable .base name service. Human-readable addresses for the Base ecosystem.",
    category: "Identity",
    founder: "Tanvi Agarwal",
    founderTwitter: "tanvinames",
    url: "https://baseens.xyz",
    batch: "Base Batch India",
    tags: ["naming", "identity"],
    logo: "BE",
    source: DEVFOLIO_LINKS.baseBatchIndia,
  },
  {
    id: "36",
    name: "Predictor",
    description: "Decentralized prediction market for Indian events — elections, cricket, weather — on Base.",
    category: "DeFi",
    founder: "Vivek Choudhary",
    founderTwitter: "vivekpredicts",
    url: "https://predictor.base",
    batch: "Base Batch India",
    tags: ["prediction", "markets"],
    logo: "PR",
    source: DEVFOLIO_LINKS.baseBatchIndia,
  },
  {
    id: "37",
    name: "CodeBounty",
    description: "Open source bounty platform on Base. Fund issues, claim bounties, build in public.",
    category: "Infra",
    founder: "Ishaan Khanna",
    founderTwitter: "ishaanbounty",
    url: "https://codebounty.dev",
    batch: "Builder Track 002",
    tags: ["bounty", "open-source"],
    logo: "CB",
    source: DEVFOLIO_LINKS.builderTrack002,
  },
  {
    id: "38",
    name: "MusicBase",
    description: "Music NFT platform for Indian artists. Release tracks, sell limited editions on Base.",
    category: "NFT",
    founder: "Reema Kapoor",
    founderTwitter: "reemamusic",
    url: "https://musicbase.xyz",
    batch: "Base Batch India",
    tags: ["music", "NFT"],
    logo: "MB",
    source: DEVFOLIO_LINKS.baseBatchIndia,
  },
  {
    id: "39",
    name: "InsureBase",
    description: "Parametric insurance on Base. Auto-payouts for crop failure, flight delays, weather events.",
    category: "DeFi",
    founder: "Ashwin Nair",
    founderTwitter: "ashwininsure",
    url: "https://insurebase.fi",
    batch: "Builder Track 002",
    tags: ["insurance", "parametric"],
    logo: "IB",
    source: DEVFOLIO_LINKS.builderTrack002,
  },
  {
    id: "40",
    name: "SkillMint",
    description: "Verifiable skill credentials as soulbound tokens on Base. Proof of expertise for Web3 jobs.",
    category: "Identity",
    founder: "Pallavi Gupta",
    founderTwitter: "pallaviskills",
    url: "https://skillmint.xyz",
    batch: "Base Batch India",
    tags: ["credentials", "soulbound"],
    logo: "SM",
    source: DEVFOLIO_LINKS.baseBatchIndia,
  },
  {
    id: "41",
    name: "BasePay",
    description: "Merchant payment gateway for Base. Accept crypto payments with instant INR settlement.",
    category: "Payments",
    founder: "Rajesh Pillai",
    founderTwitter: "rajeshpay",
    url: "https://basepay.in",
    batch: "Base Batch India",
    tags: ["payments", "merchant"],
    logo: "BP",
    source: DEVFOLIO_LINKS.baseBatchIndia,
  },
  {
    id: "42",
    name: "DataDAO",
    description: "Decentralized data marketplace. Sell anonymized datasets and earn on Base.",
    category: "DAO",
    founder: "Neeraj Sharma",
    founderTwitter: "neerajdata",
    url: "https://datadao.xyz",
    batch: "Builder Track 002",
    tags: ["data", "marketplace"],
    logo: "DD",
    source: DEVFOLIO_LINKS.builderTrack002,
  },
  {
    id: "43",
    name: "RunnerGame",
    description: "Endless runner game with NFT characters and daily leaderboard prizes on Base.",
    category: "Gaming",
    founder: "Sanjay Kumar",
    founderTwitter: "sanjayplays",
    url: "https://runnergame.xyz",
    batch: "Base Batch India",
    tags: ["gaming", "casual"],
    logo: "RG",
    source: DEVFOLIO_LINKS.baseBatchIndia,
  },
  {
    id: "44",
    name: "ChatAgent",
    description: "AI-powered customer support agent that lives on Base. Pay per conversation, no subscriptions.",
    category: "AI",
    founder: "Ayesha Khan",
    founderTwitter: "ayeshaai",
    url: "https://chatagent.base",
    batch: "Builder Track 002",
    tags: ["AI", "support"],
    logo: "CA",
    source: DEVFOLIO_LINKS.builderTrack002,
  },
  {
    id: "45",
    name: "BaseSwap",
    description: "AMM DEX native to Base with concentrated liquidity and low-fee swaps.",
    category: "DeFi",
    founder: "Vikrant Tiwari",
    founderTwitter: "vikrantswap",
    url: "https://baseswap.fi",
    batch: "Base Batch India",
    tags: ["AMM", "DEX"],
    logo: "BS",
    source: DEVFOLIO_LINKS.baseBatchIndia,
  },
  {
    id: "46",
    name: "ProofWork",
    description: "Freelancer reputation protocol. Every completed gig builds your onchain work history on Base.",
    category: "Social",
    founder: "Shreya Rao",
    founderTwitter: "shreyaproof",
    url: "https://proofwork.xyz",
    batch: "Builder Track 002",
    tags: ["reputation", "freelance"],
    logo: "PW",
    source: DEVFOLIO_LINKS.builderTrack002,
  },
  {
    id: "47",
    name: "MemeFactory",
    description: "One-click meme token launcher on Base. Fair launch with locked liquidity.",
    category: "DeFi",
    founder: "Rohit Agarwal",
    founderTwitter: "rohitmeme",
    url: "https://memefactory.fun",
    batch: "Base Batch India",
    tags: ["meme", "token-launch"],
    logo: "MF",
    source: DEVFOLIO_LINKS.baseBatchIndia,
  },
  {
    id: "48",
    name: "ChainDoc",
    description: "Verifiable document storage on Base. Diplomas, contracts, and certificates as onchain proofs.",
    category: "Identity",
    founder: "Geeta Srinivasan",
    founderTwitter: "geetadocs",
    url: "https://chaindoc.in",
    batch: "Builder Track 002",
    tags: ["documents", "verification"],
    logo: "CD",
    source: DEVFOLIO_LINKS.builderTrack002,
  },
  {
    id: "49",
    name: "TipJar",
    description: "Micro-tipping for content creators on Base. Tip anyone with a link, no wallet needed.",
    category: "Payments",
    founder: "Amar Desai",
    founderTwitter: "amartips",
    url: "https://tipjar.base",
    batch: "Base Batch India",
    tags: ["tips", "creator"],
    logo: "TJ",
    source: DEVFOLIO_LINKS.baseBatchIndia,
  },
  {
    id: "50",
    name: "BuilderBoard",
    description: "Public leaderboard tracking the most active builders on Base. Contributions, deploys, and commits.",
    category: "Infra",
    founder: "Shruti Menon",
    founderTwitter: "shrutibuilds",
    url: "https://builderboard.xyz",
    batch: "Builder Track 002",
    tags: ["leaderboard", "analytics"],
    logo: "BD",
    source: DEVFOLIO_LINKS.builderTrack002,
  },
  {
    id: "51",
    name: "OnchainKYC",
    description: "Privacy-preserving KYC protocol using ZK proofs. Verify once, use everywhere on Base.",
    category: "Identity",
    founder: "Arnav Gupta",
    founderTwitter: "arnavzk",
    url: "https://onchainkyc.xyz",
    batch: "Build Onchain FBI",
    tags: ["ZK", "KYC", "identity"],
    logo: "OK",
    source: DEVFOLIO_LINKS.buildOnchainFBI,
  },
  {
    id: "52",
    name: "BaseFi",
    description: "All-in-one DeFi dashboard for Base. Track positions, auto-harvest yields, and rebalance portfolios.",
    category: "DeFi",
    founder: "Saurabh Jain",
    founderTwitter: "saurabhdefi",
    url: "https://basefi.app",
    batch: "Build Onchain FBI",
    tags: ["DeFi", "dashboard", "yield"],
    logo: "BF",
    source: DEVFOLIO_LINKS.buildOnchainFBI,
  },
  {
    id: "53",
    name: "ChainVote",
    description: "Transparent polling and elections on Base. Gasless voting with Sybil resistance via World ID.",
    category: "DAO",
    founder: "Prateek Srivastava",
    founderTwitter: "prateekdao",
    url: "https://chainvote.app",
    batch: "Build Onchain FBI",
    tags: ["voting", "governance", "sybil"],
    logo: "CV",
    source: DEVFOLIO_LINKS.buildOnchainFBI,
  },
  {
    id: "54",
    name: "NFTGallery",
    description: "Curated virtual gallery for onchain art. 3D exhibition spaces with social viewing on Base.",
    category: "NFT",
    founder: "Ritika Bansal",
    founderTwitter: "ritikanft",
    url: "https://nftgallery.base",
    batch: "Build Onchain FBI",
    tags: ["NFT", "gallery", "3D"],
    logo: "NG",
    source: DEVFOLIO_LINKS.buildOnchainFBI,
  },
  {
    id: "55",
    name: "PaySplit",
    description: "Group expense splitting on Base. Split bills with friends, settle instantly in USDC.",
    category: "Payments",
    founder: "Mohit Tiwari",
    founderTwitter: "mohitpays",
    url: "https://paysplit.xyz",
    batch: "Build Onchain FBI",
    tags: ["payments", "social", "USDC"],
    logo: "PS",
    source: DEVFOLIO_LINKS.buildOnchainFBI,
  },
  {
    id: "56",
    name: "AgentSwarm",
    description: "Multi-agent AI framework on Base. Deploy swarms of AI agents that collaborate onchain.",
    category: "AI",
    founder: "Divyansh Mehta",
    founderTwitter: "divyanshagent",
    url: "https://agentswarm.ai",
    batch: "Build Onchain FBI",
    tags: ["AI", "agents", "multi-agent"],
    logo: "AS",
    source: DEVFOLIO_LINKS.buildOnchainFBI,
  },
  {
    id: "57",
    name: "BaseStream",
    description: "Decentralized live streaming with token-gated access and real-time tipping on Base.",
    category: "Social",
    founder: "Anjali Verma",
    founderTwitter: "anjalistream",
    url: "https://basestream.live",
    batch: "Build Onchain FBI",
    tags: ["streaming", "social", "tipping"],
    logo: "BT",
    source: DEVFOLIO_LINKS.buildOnchainFBI,
  },
  {
    id: "58",
    name: "StackBase",
    description: "DCA and dollar-cost averaging protocol for Base. Auto-buy any token on a schedule.",
    category: "DeFi",
    founder: "Kartikey Sharma",
    founderTwitter: "kartikeydefi",
    url: "https://stackbase.fi",
    batch: "Build Onchain FBI",
    tags: ["DCA", "DeFi", "automation"],
    logo: "SB",
    source: DEVFOLIO_LINKS.buildOnchainFBI,
  },
  {
    id: "59",
    name: "QuestDrop",
    description: "Gamified airdrop distribution. Complete onchain quests to earn token drops on Base.",
    category: "Gaming",
    founder: "Raghav Mittal",
    founderTwitter: "raghavquest",
    url: "https://questdrop.xyz",
    batch: "Build Onchain FBI",
    tags: ["quests", "airdrops", "gamification"],
    logo: "QD",
    source: DEVFOLIO_LINKS.buildOnchainFBI,
  },
  {
    id: "60",
    name: "BaseRelay",
    description: "Gasless transaction relay network for Base dApps. Sponsor gas for your users seamlessly.",
    category: "Infra",
    founder: "Nitin Rawat",
    founderTwitter: "nitinrelay",
    url: "https://baserelay.dev",
    batch: "Build Onchain FBI",
    tags: ["gas", "relay", "infra"],
    logo: "RL",
    source: DEVFOLIO_LINKS.buildOnchainFBI,
  },
  {
    id: "61",
    name: "OnchainResume",
    description: "Verifiable professional credentials on Base. Your work history as soulbound attestations.",
    category: "Identity",
    founder: "Megha Sinha",
    founderTwitter: "meghacreds",
    url: "https://onchainresume.xyz",
    batch: "Build Onchain FBI",
    tags: ["credentials", "resume", "attestations"],
    logo: "OR",
    source: DEVFOLIO_LINKS.buildOnchainFBI,
  },
  {
    id: "62",
    name: "TokenChat",
    description: "Token-gated community messaging on Base. Hold tokens to access exclusive group chats.",
    category: "Social",
    founder: "Aryan Khanna",
    founderTwitter: "aryanchat",
    url: "https://tokenchat.xyz",
    batch: "Build Onchain FBI",
    tags: ["messaging", "token-gated", "community"],
    logo: "TC",
    source: DEVFOLIO_LINKS.buildOnchainFBI,
  },
  {
    id: "63",
    name: "BaseBets",
    description: "Peer-to-peer betting protocol on Base. Create custom bets, invite friends, settle trustlessly.",
    category: "Gaming",
    founder: "Siddharth Goyal",
    founderTwitter: "sidbets",
    url: "https://basebets.gg",
    batch: "Build Onchain FBI",
    tags: ["betting", "P2P", "gaming"],
    logo: "BG",
    source: DEVFOLIO_LINKS.buildOnchainFBI,
  },
  {
    id: "64",
    name: "MintPress",
    description: "No-code NFT collection deployer for Base. Upload art, set rules, launch in minutes.",
    category: "NFT",
    founder: "Tara Saxena",
    founderTwitter: "taramints",
    url: "https://mintpress.art",
    batch: "Build Onchain FBI",
    tags: ["NFT", "no-code", "deployer"],
    logo: "MP",
    source: DEVFOLIO_LINKS.buildOnchainFBI,
  },
  {
    id: "65",
    name: "PromptPay",
    description: "Pay AI agents with crypto on Base. Micropayments for API calls, prompts, and compute.",
    category: "AI",
    founder: "Yash Agarwal",
    founderTwitter: "yashprompt",
    url: "https://promptpay.base",
    batch: "Build Onchain FBI",
    tags: ["AI", "micropayments", "agents"],
    logo: "PP",
    source: DEVFOLIO_LINKS.buildOnchainFBI,
  },
];

export const founders: Founder[] = projects.map((p) => ({
  id: p.id,
  name: p.founder,
  twitter: p.founderTwitter,
  avatar: p.name
    .split(" ")
    .map((w) => w[0])
    .join("")
    .slice(0, 2)
    .toUpperCase(),
  role: "Builder",
  project: p.name,
}));
